if(EXISTS "/home/ynachi/codes/kio/build2/bitcask/tests/partition_integration_test[1]_tests.cmake")
  include("/home/ynachi/codes/kio/build2/bitcask/tests/partition_integration_test[1]_tests.cmake")
else()
  add_test(partition_integration_test_NOT_BUILT partition_integration_test_NOT_BUILT)
endif()
