if(EXISTS "/home/ynachi/codes/kio/build2/tests/buffer_pool_test[1]_tests.cmake")
  include("/home/ynachi/codes/kio/build2/tests/buffer_pool_test[1]_tests.cmake")
else()
  add_test(buffer_pool_test_NOT_BUILT buffer_pool_test_NOT_BUILT)
endif()
