if(EXISTS "/home/ynachi/codes/kio/build2/tests/kio_logger_test[1]_tests.cmake")
  include("/home/ynachi/codes/kio/build2/tests/kio_logger_test[1]_tests.cmake")
else()
  add_test(kio_logger_test_NOT_BUILT kio_logger_test_NOT_BUILT)
endif()
