if(EXISTS "/home/ynachi/codes/kio/build2/tests/sync_wait_test[1]_tests.cmake")
  include("/home/ynachi/codes/kio/build2/tests/sync_wait_test[1]_tests.cmake")
else()
  add_test(sync_wait_test_NOT_BUILT sync_wait_test_NOT_BUILT)
endif()
